# Аугментации для анализа семантики.
experiment:
  type: paraphrase

model:
  path: /userspace/pes/diploma_materials/Qwen3-4B

dataset:
  path: /userspace/pes/diploma_materials/dolly_dataset/train/data-00000-of-00001.arrow

training:
  samples: 70
  seed: 42
  aug_number: 6
  paraphrase_number: 9
  generation:
    max_new_tokens: 4096
    temperature: 0.7
    top_p: 0.9

logging:
  save_path: /userspace/pes/diploma/data/paraphrase_dataset
  checkpoint_file: /userspace/pes/diploma/data/paraphrase_ckpt.jsonl
  checkpoint_step: 10
