model:
  path: /userspace/pes/diploma_materials/models/qwen3_embedder_4b
  dtype: bfloat16

dataset:
  path: /userspace/pes/diploma/results/dolly_llama_nar_exp1.json
  type: dolly

task_type: end2end

training:
  batch_size: 16
  normalize: True

logging:
  save_path: /userspace/pes/diploma/results/dolly_teacher_embeddings.json