# configs/dolly_end2end.yaml

model:
  encoder_path: /userspace/pes/diploma_materials/models/Llama-3.2-1B
  decoder_path: /userspace/pes/diploma_materials/models/Llama-3.2-1B
  dtype: bfloat16

dataset:
  path: /userspace/pes/diploma_materials/datasets/dolly_data
  type: dolly

task_type: end2end

training:
  batch_size: 8
  num_epochs: 50
  max_tokens: 256
  seed: 42

# Надо переписать
# logging:
#   save_every: 10
#   save_log_path: /userspace/pes/diploma/logs/end2end_dolly_exp.json
#   save_path: /userspace/pes/diploma/results/end2end_dolly_exp.json