model:
  path: /userspace/pes/diploma_materials/models/Llama-3.2-1B-Instruct
  dtype: bfloat16

dataset:
  path: /userspace/pes/diploma/results/dolly_llama_nar_exp1.json
  type: dolly

task_type: end2end

training:
  batch_size: 6
  max_tokens: 256
  n_epochs: 20
  seed: 42
  diversity_loss_weight: 0.1
  code_books:
    G: 2
    V: 32
    tau: 1.0
    m_vector: False

logging:
  save_every: 10
  save_log_path: /userspace/pes/diploma/logs/dolly_llama_codebook_exp.log
  save_path: /userspace/pes/diploma/results/dolly_llama_codebook_exp.log